#!/usr/bin/env bash
# FizzBuzz numbers
num=1
while [ $num -e 100]
then
	if [ $((num % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ]; then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ]; then
		echo "Fizz"
	else
		echo $i
	fi
	num=$((num + 1))
done
